### ISSUE TITLE
Nothing been added into the database

### ISSUE THREAD

**Issue by ritchieprimelab** [Adamant-im/ETH-transactions-storage#10]
Hi there, I'm facing an issue when setting it up
I have the service running, starting block set to 100000, service is running but seems like there is nothing gets written into the database, This is the only log i can see 
022-07-02 03:01:31,283 - INFO - Current best block in index: 1000000; in Ethereum chain: 0

I'm setting it up on a fully synced node via geth. Any help would be appreciated

**Comment by adamant-al** [comment]
Hi! It seems you've not set a connection to Ethereum node.
We've updated installation instructions, follow them once again: https://github.com/Adamant-im/ETH-transactions-storage#installation
