### ISSUE TITLE
Some remarks on: contract value and running the indexer,

### ISSUE THREAD

**Issue by OGalbert** [Adamant-im/ETH-transactions-storage#12]
Hi Adamant,
First of all, I wanna say thank you for putting this indexer public.
Secondly, I found some major practical issues, which might be interesting to everyone using this:

The first issue is the contract value. This script doesn't include the number of decimals of the ERC20 contracts. Some contracts (USDT) use 6 decimals, whereas others use 18. So anyone using this, should be aware. Fixing this could be done either within this script or on the database side, with a list of erc20 contracts of interest and their number of decimals. 

Second issue is that this script will never be able to reach the newest blocks of the chain, due to the slow process of synchronously fetching the status of each individual transaction in a loop. I recommand either skipping the getTransactionReceipt() function (and thus the loop) and batch inserting the transaction list from the fetched block into the database, or rewriting the entire code in async (which is nice anyway :))

**Comment by adamant-al** [comment]
Hi, thank you for suggestion.

1) Indexer stores "contract_value" in hex: "000000000000000000000000000000000000000000000000149acd7c15f4c000". Then you convert into dex 1484724960000000000, and then consider decimals depending on contract. Client software can do that.

2) Use fast server and it will. Take attention that Ethereum node itself has high server requirements, that's the reality. Ethereum doesn't has API for batch getting txs info including receipts/statuses.
