### ISSUE TITLE
web3.eth camelCasing

### ISSUE THREAD

**Issue by DAR-tatum** [Adamant-im/ETH-transactions-storage#16]
The web3.py package updated its methods and all calls previously in camelCase are now in snake_case causing the indexer to fail. The data returned by the methods is still in the same format.

**Comment by adamant-al** [comment]
Hi,

Please make a PR to update with these changes.

**Comment by adamant-al** [comment]
Fixed with 
https://github.com/Adamant-im/ETH-transactions-storage/pull/17
https://github.com/Adamant-im/ETH-transactions-storage/pull/18
