### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by drewwells** [Adamant-im/ETH-transactions-storage#3]
Docker makes it possible to contain the entire project into a docker-compose.yml. This compose file would start a database postgresql in a container, and eth-transactions-storage in a container. Compose would allow the two to communicate and significantly reduce Quickstart guide to the project.

Has anyone containerized the application? I could throw together a compose file to start it up.

**Comment by ensingerphilipp** [comment]
This would actually be super useful

**Comment by adamant-al** [comment]
Welcome to contribute with docker file.

**Comment by guenoledc** [comment]
Hi

I was starting to do this docker-compose file but there are a number of changes that needs to be made to the python file

- connecting to the eth node
- setting the initial block to start from
- the end block should not be the last block in my opinion but the last block considered with enough confirmations (3 or more blocks)
My python is a little rusty so ...

Also I am not sure using the postgres generic api exposure convenient. I need to look into this.

I will try and publish some results in a separate branch, if I may

**Comment by drewwells** [comment]
I ended up mounting a volume with the last block file. Ideally, the data and state would be stored in the same place ie. postgres or be read only like an environment variable or static file we preload in the container. This would eliminate the need for multiple sources of read/write container state persistence.

 thegraph stores state in a separate database table. It solves issues with restarts. The initial state of the world is predefined in a static config file or environment variables. This allows you to give a default starting block, but after initial runs have happened, the state of the database is taken as the starting block rather than starting over again from the config file.

**Comment by guenoledc** [comment]
> I ended up mounting a volume with the last block file. Ideally, the data and state would be stored in the same place ie. postgres or be read only like an environment variable or static file we preload in the container. This would eliminate the need for multiple sources of read/write container state persistence.
> 
> thegraph stores state in a separate database table. It solves issues with restarts. The initial state of the world is predefined in a static config file or environment variables. This allows you to give a default starting block, but after initial runs have happened, the state of the database is taken as the starting block rather than starting over again from the config file.

Hi @drewwells , can you ellaborate? I don't fully comprehend your comment

**Comment by dev-adamant-im** [comment]
@drewwells @guenoledc We've gave you `write` access to the repository, so it seems you can create new branches.
As for `the end block should not be the last block in my opinion but the last block considered with enough confirmations (3 or more blocks)` I believe it should be optional, as we need to get txs as fast as possible.
Better if script admin can set up parameters.

**Comment by drewwells** [comment]
@guenoledc I thought a diagram would help articulate my point. I realize the explanation provided was not very good. For containers, it's quite easy to provide them read access to some data. For example, a static file provided in the container itself, environment variables, volume mounting a k8s configmap for some read only data.

If the container needs to write down something or maintain state, ie. last_block_mined. You need to provide a place to store it.

![image](https://user-images.githubusercontent.com/239123/130667931-d250403a-846f-40e5-8d1c-c90704ba4f45.png)

In this photo, I'm loading config information into the eth tx container. This is a one way relationship, read only. It's easy to provide this type of data with things like k8s configmap or secret. 


![image](https://user-images.githubusercontent.com/239123/130668629-d8e8b9b1-7d2c-4359-9944-9605ea56e411.png)


For any state that needs to be maintained, I write that out to the available storage media. On application start, postgresql is selected. On start of the application, have it attempt to create a table with `chain_state` with columns `|ID|Chain|last_block`. If the table already exists, fail silently at attempting to create this table. When the application is deciding what block to check for, it checks the chain/ID being tracked and looks for it in the table. If there is nothing, then use the starting position from the config. If there is a record, then use the recorded position from the table. On successful scraping of the chain blocks, record the last position in postgresql like it's done today in the file.

**Comment by guenoledc** [comment]
Submitted a dockerized setup on #6

**Comment by adamant-al** [comment]
Done https://github.com/Adamant-im/ETH-transactions-storage/pull/6
