### ISSUE TITLE
Transaction log

### ISSUE THREAD

**Issue by artemg** [Adamant-im/ETH-transactions-storage#7]
Hi, @adamant-al . By looing into the indexer https://github.com/Adamant-im/ETH-transactions-storage/blob/master/ethsync.py#L108 it seems like you identify token transfers by looking into transaction input data. As such transfers may fail, should the code inspect transaction logs and look for Transfer event instead?

**Comment by adamant-al** [comment]
Hi,
Indexer saves all of transfers/transactions, including failed. For filtering success transfers, use `status` field.
Does it answer your request?
Or it's not about this?
