### ISSUE TITLE
Any estimates on how long the indexer will take to run from genesis?

### ISSUE THREAD

**Issue by satwikkansal** [Adamant-im/ETH-transactions-storage#8]
First of all thanks for putting up the project :)

The readme says,

>  First Indexer will store transactions starting from block you set. It will take a time.

Is it possible to have a rough idea to know how long would it take to index the entire chain? Or if you have tried that already, would be keen to know how long it took you and what were the specs of the machine that you used.

**Comment by adamant-al** [comment]
Hi!
Never synced it from the Ethereum genesis. I think it will require several days or even week on a decent machine.
